name: kantin_app
description: "A new Flutter project."
publish_to: "none"
version: 3.4.4

environment:
  sdk: ^3.6.0-198.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
